project_name: "multi_task_lasa"

dataset:
  name: "multitask_lasa"
  pattern_names: ["GShape", "Sine"]
  train_indices: [0, 2, 4]
  val_indices: [1]
  test_indices: [3, 6]
  chunk_size: 16
  action_dim: 6
  state_dim: 6
  use_velocity: true
  use_acceleration: true

model:
  hidden_dim: 512
  num_layers: 8
  num_heads: 2
  num_classes: 10

training:
  batch_size: 512
  epochs: 1000
  lr: 1.e-4
  device: "cuda"
  weight_decay: 0.01
inference:
  sampling_steps: 5
  k_step: 2